Repository spring-cloud/spring-cloud-contract, pull requests merged in 2018-11, with the labels that each got.

#780 Improved spring-cloud-wiremock documentation
  docs/src/main/asciidoc/spring-cloud-wiremock.adoc
Labels: documentation

#786 Added support for camel with Boot 2.0; gh-673
  docs/src/main/asciidoc/migrations.adoc
  docs/src/main/asciidoc/verifier_stubrunner_msg.adoc
  pom.xml
  spring-cloud-contract-stub-runner/pom.xml
  spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/camel/StubRunnerCamelConfiguration.java
  spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/camel/StubRunnerCamelPredicate.java
  spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/camel/StubRunnerCamelProcessor.java
  spring-cloud-contract-stub-runner/src/main/resources/META-INF/spring.factories
  spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/camel/StubRunnerCamelPredicateSpec.groovy
  spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/serverexamples/StubRunnerBootConsulExample.java
  spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/serverexamples/StubRunnerBootEurekaExample.java
  spring-cloud-contract-stub-runner/src/test/groovy/org/springframework/cloud/contract/stubrunner/serverexamples/StubRunnerBootZookeeperExample.java
  spring-cloud-contract-verifier/pom.xml
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/camel/CamelStubMessages.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/camel/ContractVerifierCamelConfiguration.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/camel/ContractVerifierCamelMessageBuilder.java
  spring-cloud-contract-verifier/src/main/resources/META-INF/spring.factories
  tests/pom.xml
  tests/samples-messaging-camel/.springBeans
  tests/samples-messaging-camel/pom.xml
  tests/samples-messaging-camel/src/main/java/com/example/BookDeleted.java
  tests/samples-messaging-camel/src/main/java/com/example/BookDeleter.java
  tests/samples-messaging-camel/src/main/java/com/example/BookReturned.java
  tests/samples-messaging-camel/src/main/java/com/example/BookRouteConfiguration.java
  tests/samples-messaging-camel/src/main/java/com/example/BookService.java
  tests/samples-messaging-camel/src/main/java/com/example/CamelMessagingApplication.java
  tests/samples-messaging-camel/src/test/groovy/com/example/CamelMessagingApplicationSpec.groovy
  tests/spring-cloud-contract-stub-runner-camel/README.adoc
  tests/spring-cloud-contract-stub-runner-camel/pom.xml
  tests/spring-cloud-contract-stub-runner-camel/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/camel/BookReturned.groovy
  tests/spring-cloud-contract-stub-runner-camel/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/camel/CamelStubRunnerSpec.groovy
  tests/spring-cloud-contract-stub-runner-camel/src/test/groovy/org/springframework/cloud/contract/stubrunner/messaging/camel/StubRunnerCamelProcessorSpec.groovy
  tests/spring-cloud-contract-stub-runner-camel/src/test/resources/application.yml
  tests/spring-cloud-contract-stub-runner-camel/src/test/resources/m2repo/repository/org/springframework/cloud/contract/verifier/stubs/camelService/0.0.1-SNAPSHOT/camelService-0.0.1-SNAPSHOT-stubs.jar
  tests/spring-cloud-contract-stub-runner-camel/src/test/resources/m2repo/repository/org/springframework/cloud/contract/verifier/stubs/camelService/0.0.1-SNAPSHOT/camelService-0.0.1-SNAPSHOT.pom
  tests/spring-cloud-contract-stub-runner-camel/src/test/resources/m2repo/repository/org/springframework/cloud/contract/verifier/stubs/camelService/0.0.1-SNAPSHOT/maven-metadata-local.xml
  tests/spring-cloud-contract-stub-runner-camel/src/test/resources/m2repo/repository/org/springframework/cloud/contract/verifier/stubs/camelService/maven-metadata-local.xml
  tests/spring-cloud-contract-stub-runner-camel/src/test/resources/m2repo/repository/org/springframework/cloud/contract/verifier/stubs/camelService/maven-metadata.xml
Labels: enhancement

#805 fix stub runner application when is in real stream mode
  spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/messaging/StubRunnerStreamsIntegrationAutoConfiguration.java
Labels: waiting-for-triage
