Repository spring-cloud/spring-cloud-contract, pull requests merged in 2018-12, with the labels that each got.

#808 small fix in doc
  docs/src/main/asciidoc/verifier_setup.adoc
Labels: documentation

#814 Move aether deps from dependencies pom to parent pom.
  pom.xml
  spring-cloud-contract-dependencies/pom.xml
Labels: in progress

#812 Configure for WireMockServer instead of port
  spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockConfiguration.java
Labels: waiting-for-triage
