Repository spring-cloud/spring-cloud-contract, pull requests merged in 2018-05, with the labels that each got.

#624 Avoid body parsing for HEAD request
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientJUnitMethodBodyBuilder.groovy
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientSpockMethodRequestProcessingBodyBuilder.groovy
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/RequestProcessingMethodBodyBuilder.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
Labels: enhancement

#642 Credential properties for pact broker
  docs/src/main/asciidoc/verifier_contract.adoc
  spring-cloud-contract-tools/spring-cloud-contract-pact/src/main/groovy/org/springframework/cloud/contract/stubrunner/PactStubDownloaderBuilder.java
  spring-cloud-contract-tools/spring-cloud-contract-pact/src/test/groovy/org/springframework/cloud/contract/stubrunner/PactStubDownloaderBuilderSpec.groovy
Labels: enhancement, waiting for feedback

#644 Matchers documentation improvements
  docs/src/main/asciidoc/verifier_contract.adoc
Labels: documentation, waiting for feedback

#648 Updated documentation for generating Spring REST Docs snippets
  docs/src/main/asciidoc/spring-cloud-contract-verifier.adoc
  docs/src/main/asciidoc/verifier_contract.adoc
  samples/standalone/restdocs/http-server/build.gradle
  samples/standalone/restdocs/http-server/pom.xml
  samples/standalone/restdocs/http-server/src/test/java/com/example/fraud/FraudBaseWithStandaloneSetup.java
  samples/standalone/restdocs/http-server/src/test/java/com/example/fraud/FraudBaseWithWebAppSetup.java
  samples/standalone/restdocs/http-server/src/test/resources/contracts/standalone/shouldMarkClientAsFraud.groovy
  samples/standalone/restdocs/http-server/src/test/resources/contracts/webapp/shouldMarkClientAsNotFraud.groovy
Labels: documentation

#653 Added assertion for empty map/object to autogenerated test
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverter.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MockMvcMethodBodyBuilderSpec.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverterSpec.groovy
Labels: bug

#654 Generated numbers shouldn't be quoted in the stub
  spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockResponseStubStrategySpec.groovy
Labels: bug

#656 Fix `pluginGroups` entry info. Fix plugin call examples. Add info about
  spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/site/asciidoc/usage.adoc
Labels: documentation
