Repository spring-cloud/spring-cloud-contract, pull requests merged in 2018-07, with the labels that each got.

#684 Move YamlContractConverter list of available contract converters.
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/file/ContractFileScanner.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/file/ContractFileScannerSpec.groovy
  spring-cloud-contract-verifier/src/test/resources/directory/with/custom/yml/custom.yml
Labels: bug

#687 Move YamlContractConverter after available contract converters for producers
  spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRepository.java
  spring-cloud-contract-stub-runner/src/test/java/org/springframework/cloud/contract/stubrunner/StubRepositoryTest.java
  spring-cloud-contract-stub-runner/src/test/java/org/springframework/cloud/contract/stubrunner/TestCustomYamlContractConverter.java
  spring-cloud-contract-stub-runner/src/test/resources/META-INF/spring.factories
  spring-cloud-contract-stub-runner/src/test/resources/customYamlRepository/contracts/custom.yml
Labels: enhancement

#692 Fix using regex patterns when matching raw body value
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JUnitMethodBodyBuilder.groovy
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/RestAssuredJUnitMethodBodyBuilder.groovy
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/SpockMethodRequestProcessingBodyBuilder.groovy
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/RegexpBuilders.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MethodBodyBuilderSpec.groovy
Labels: bug, in progress

#693 Made stream binder optional
  spring-cloud-contract-starters/spring-cloud-starter-contract-stub-runner/pom.xml
Labels: enhancement, in progress
