Repository spring-cloud/spring-cloud-contract, pull requests merged in 2019-09, with the labels that each got.

#1223 SCC Verifier Docker now publishes stubs just once
  docker/spring-cloud-contract-docker/project/build.gradle
Labels: enhancement

#1220 Fix links to http-server and http-client samples in doc
  docs/src/main/asciidoc/getting-started.adoc
Labels: bug, documentation

#1226 Using same Maven version as Boot
  pom.xml
  spring-cloud-contract-dependencies/pom.xml
Labels: bug, dependencies

#1229 Fix flattened size counter. Fixes gh-1108.
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/assertion/CollectionAssert.java
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/assertion/CollectionAssertTests.java
Labels: enhancement
