Repository spring-cloud/spring-cloud-contract, pull requests merged in 2019-06, with the labels that each got.

#1100 Update pom.xml
  samples/standalone/contracts/com/example/server/pom.xml
Labels: enhancement

#1107 Fixed issue with content is not allowed in prolog for body from the xml file
  spring-cloud-contract-spec/src/main/groovy/org/springframework/cloud/contract/spec/internal/FromFileProperty.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockGroovyDslSpec.groovy
  spring-cloud-contract-verifier/src/test/resources/classpath/request.xml
Labels: bug

#1110 Fixed MissingMethodExceptionNoStack at creating assertion for spock test
  spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/spring-boot-groovy/src/main/java/hello/GreetingController.java
  spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/spring-boot-groovy/src/main/java/hello/GreetingResponse.java
  spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/spring-boot-groovy/src/test/resources/contracts/greetings_post_ok.groovy
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/assertion/SpringCloudContractAssertions.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/assertion/CollectionAssertSpec.groovy
Labels: waiting-for-triage

#1113 Matching strategy at body and contentType issue
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockRequestStubStrategy.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/dsl/wiremock/WireMockGroovyDslSpec.groovy
Labels: waiting-for-triage
