Repository spring-cloud/spring-cloud-contract, pull requests merged in 2020-12, with the labels that each got.

#1558 Attempt to keep Kotlin totally off the classpath
  samples/standalone/dsl/http-client/build.gradle
  samples/standalone/dsl/http-client/settings.gradle
  samples/standalone/dsl/http-server/build.gradle
  samples/standalone/dsl/http-server/settings.gradle
  samples/standalone/restdocs/http-server/build.gradle
  samples/standalone/restdocs/http-server/pom.xml
  samples/standalone/restdocs/http-server/settings.gradle
  samples/standalone/restdocs/http-server/src/test/java/com/example/fraud/StubGeneratorTests.java
  samples/standalone/webclient/http-client/build.gradle
  samples/standalone/webclient/http-client/settings.gradle
  samples/standalone/webclient/http-server/build.gradle
  samples/standalone/webclient/http-server/pom.xml
  samples/standalone/webclient/http-server/settings.gradle
  scripts/gradleOnly.sh
  spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/converter/RecursiveFilesConverterApplication.java
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build.gradle
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/gradle/release.gradle
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/pom.xml
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateClientStubsFromDslTask.java
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateServerTestsTask.java
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/VersionExtractor.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/TestGeneratorApplication.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/ToYamlConverterApplication.java
Labels: enhancement

#1578 Removes the exclusions of old asm lib from jsonpath lib.
  spring-cloud-contract-dependencies/pom.xml
  spring-cloud-contract-starters/spring-cloud-starter-contract-verifier/pom.xml
  spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/complex-configuration/pom.xml
  spring-cloud-contract-tools/spring-cloud-contract-maven-plugin/src/test/projects/different-module-configuration/module/pom.xml
  spring-cloud-contract-verifier/pom.xml
Labels: wontfix

#1577 Adds info note in Wiremock docs around use of WireMock.resetToDefaultMappings
  docs/src/main/asciidoc/_project-features-wiremock.adoc
Labels: documentation

#1581 Generates random boolean request value for aBoolean()
  specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/PatternValueDslProperty.java
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SpringTestMethodBodyBuildersSpec.groovy
Labels: bug

#1575 Added a section "Cloning the repository on Windows" for issue#1567
  docs/src/main/asciidoc/_building.adoc
Labels: documentation

#1584 Add javadoc for AutoConfigureWireMock
  spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMock.java
Labels: documentation
