Repository spring-cloud/spring-cloud-contract, pull requests merged in 2020-07, with the labels that each got.

#1445 bug: handle xml with namespaces closes #1427
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverter.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverterSpec.groovy
Labels: waiting-for-triage

#1442 Wording changes
  docs/src/main/asciidoc/_project-features-contract.adoc
  docs/src/main/asciidoc/_project-features-messaging.adoc
  docs/src/main/asciidoc/_project-features-stubrunner.adoc
  docs/src/main/asciidoc/docker-project.adoc
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/ghpages.sh
  docs/src/main/asciidoc/gradle-project.adoc
  docs/src/main/asciidoc/howto.adoc
  docs/src/main/asciidoc/maven-project.adoc
  docs/src/main/asciidoc/project-features.adoc
  docs/src/main/asciidoc/using.adoc
Labels: documentation

#1456 no length limit in ISO8601_WITH_OFFSET second's decimal fraction
  specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/RegexPatterns.java
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/JaxRsClientMethodBuilderSpec.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/MessagingMethodBodyBuilderSpec.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SpringTestMethodBodyBuildersSpec.groovy
Labels: bug

#1450 Editing pass
  docs/src/main/asciidoc/_additional-stubrunner-configprops.adoc
  docs/src/main/asciidoc/_configprops.adoc
  docs/src/main/asciidoc/_index.adoc
  docs/src/main/asciidoc/_project-features-contract.adoc
  docs/src/main/asciidoc/_project-features-flows.adoc
  docs/src/main/asciidoc/_project-features-messaging.adoc
  docs/src/main/asciidoc/_project-features-stubrunner.adoc
  docs/src/main/asciidoc/_project-features-wiremock.adoc
  docs/src/main/asciidoc/advanced.adoc
  docs/src/main/asciidoc/docker-project.adoc
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/gradle-project.adoc
  docs/src/main/asciidoc/howto.adoc
  docs/src/main/asciidoc/maven-project.adoc
  docs/src/main/asciidoc/project-features.adoc
  docs/src/main/asciidoc/using.adoc
Labels: waiting-for-triage

#1446 bug: handle xml with namespaces for validations #1427
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/XmlBodyVerificationBuilder.java
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverter.groovy
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/ContractVerifierUtil.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/xml/DOMNamespaceContext.java
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/converter/YamlContractConverterSpec.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/util/xml/XmlToXPathsConverterSpec.groovy
  spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/builder/XmlBodyVerificationBuilderTest.java
  spring-cloud-contract-verifier/src/test/java/org/springframework/cloud/contract/verifier/util/ContractVerifierUtilTest.java
  spring-cloud-contract-verifier/src/test/resources/yml/contract_rest_named_xml.yml
Labels: waiting-for-triage
