Repository spring-cloud/spring-cloud-contract, pull requests merged in 2020-11, with the labels that each got.

#1531 Migrate DSL contracts to 'contractTest' source set
  docs/src/main/asciidoc/_project-features-contract.adoc
  docs/src/main/asciidoc/gradle-project.adoc
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build.gradle
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractVerifierExtension.java
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java
Labels: enhancement

#1554 Fixes for remote contracts
  docs/src/main/asciidoc/_project-features-contract.adoc
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/ContractsCopyTask.java
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java
Labels: enhancement

#1556 Adds handling for empty list and empty map response body
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/builder/JsonBodyVerificationBuilder.java
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/JsonToJsonPathsConverter.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/SpringTestMethodBodyBuildersSpec.groovy
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/builder/YamlMockMvcMethodBodyBuilderSpec.groovy
Labels: bug

#1560 Fix stubsDir for publishStubsToScmTask.
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java
Labels: bug

#1563 Support auto configuration on meta-annotations
  spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockTestExecutionListener.java
  spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/MetaAnnotationWithResetAfterEachTestApplicationTests.java
Labels: waiting-for-triage

#1566 Allows @AutoConfigureWireMock to respect user-specified properties
  spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMock.java
  spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/AutoConfigureWireMockConfigurationInYamlTests.java
  spring-cloud-contract-wiremock/src/test/resources/application-customfoo.yml
  spring-cloud-contract-wiremock/src/test/resources/custom-from-yml/__files/hello-custom.json
  spring-cloud-contract-wiremock/src/test/resources/custom-from-yml/mappings/custom-test-endpoint.json
Labels: bug

#1564 Support auto configuration on meta-annotations
  spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockTestExecutionListener.java
  spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/MetaAnnotationWithResetAfterEachTestApplicationTests.java
Labels: bug
