Repository spring-cloud/spring-cloud-contract, pull requests merged in 2020-08, with the labels that each got.

#1464 Disable stubsJar publication by default.
  docs/src/main/asciidoc/gradle-project.adoc
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/ContractVerifierExtension.java
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/groovy/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.groovy
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/groovy/org/springframework/cloud/contract/verifier/plugin/ContractVerifierSpec.groovy
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/resources/functionalTest/scenarioProject/build.gradle
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/test/resources/functionalTest/scenarioProjectKotlin/build.gradle.kts
Labels: breaking change, enhancement

#1471 Rewrite WireMockToDslConverter to Java
  spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/groovy/org/springframework/cloud/contract/verifier/wiremock/WireMockToDslConverter.groovy
  spring-cloud-contract-tools/spring-cloud-contract-converters/src/main/java/org/springframework/cloud/contract/verifier/wiremock/WireMockToDslConverter.java
Labels: enhancement

#1478 Convert groovy to java (spring-cloud-contract-verifier module)
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/ToYamlConverter.groovy
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/converter/YamlContractConverter.groovy
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/NamesUtil.groovy
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/ToYamlConverter.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/YamlContract.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/converter/YamlContractConverter.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/NamesUtil.java
Labels: enhancement

#1481 Convert groovy to java (spring-cloud-contract-verifier module)
  spring-cloud-contract-verifier/src/main/groovy/org/springframework/cloud/contract/verifier/util/ContractScanner.groovy
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/ContentType.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/ContractScanner.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/DslParseException.java
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/util/JsonPaths.java
Labels: waiting-for-triage

#1484 Change related to issue 1483
  docs/src/test/java/org/springframework/cloud/contract/docs/AdditionalResourcesGenerationTests.java
Labels: documentation
