Repository spring-cloud/spring-cloud-contract, pull requests merged in 2021-08, with the labels that each got.

#1688 Add support for v4 UUIDs, and allow UUIDs to be case insensitive
  specs/spring-cloud-contract-spec-java/src/main/java/org/springframework/cloud/contract/spec/internal/RegexPatterns.java
  specs/spring-cloud-contract-spec/src/test/groovy/org/springframework/cloud/contract/spec/internal/RegexPatternsSpec.groovy
Labels: enhancement

#1686 Fixed typo in gradle example
  docs/src/main/asciidoc/gradle-project.adoc
Labels: waiting-for-triage

#1691 fix #1690: removes all links to scc workshop
  README.adoc
  docs/src/main/asciidoc/README.adoc
  docs/src/main/asciidoc/getting-started.adoc
  docs/src/main/asciidoc/using.adoc
Labels: waiting-for-triage

#1694 fixes #1639: run with unprivileged user and bump java version to 8.0.292.hs
  docker/spring-cloud-contract-docker/Dockerfile
  docker/spring-cloud-contract-docker/pom.xml
  docker/spring-cloud-contract-docker/sdkman/sdkman-exec.sh
  docker/spring-cloud-contract-docker/sdkman/sdkman-wrapper.sh
  docker/spring-cloud-contract-stub-runner-docker/Dockerfile
  docker/spring-cloud-contract-stub-runner-docker/run.sh
  docker/spring-cloud-contract-stub-runner-docker/sdkman/sdkman-exec.sh
  docker/spring-cloud-contract-stub-runner-docker/sdkman/sdkman-wrapper.sh
Labels: waiting-for-triage

#1695 Fixes #1672: allow users to specify a custom build.gradle when using standalone docker image
  docker/spring-cloud-contract-docker/Dockerfile
  docker/spring-cloud-contract-docker/project/README.adoc
  docker/spring-cloud-contract-stub-runner-docker/Dockerfile
  docs/src/main/asciidoc/docker-project.adoc
Labels: waiting-for-triage

#1707 Fix JGit integration
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/build.gradle
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/pom.xml
Labels: bug
