Repository spring-cloud/spring-cloud-contract, pull requests merged in 2021-03, with the labels that each got.

#1617 Add kotlin-scripting-compiler-embeddable for Kotlin DSL
  docs/src/main/asciidoc/_project-features-contract.adoc
  docs/src/main/asciidoc/gradle-project.adoc
Labels: documentation

#1618 Fix Clone on Windows instructions
  README.adoc
Labels: documentation

#1622 Fixing typo on contractsProperties
  docs/src/main/asciidoc/maven-project.adoc
Labels: waiting-for-triage

#1623 Add support for comparing byte[] Kafka message header values
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaConfiguration.java
  spring-cloud-contract-verifier/src/test/groovy/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaHelperSpec.groovy
Labels: bug

#1624 Spelling and grammar fixes
  docs/src/main/asciidoc/getting-started.adoc
Labels: waiting-for-triage

#1629 Handle null kafka header values
  spring-cloud-contract-verifier/src/main/java/org/springframework/cloud/contract/verifier/messaging/kafka/ContractVerifierKafkaConfiguration.java
Labels: bug

#1631 Fix Clone on Windows instructions
  docs/src/main/asciidoc/_building.adoc
Labels: documentation
