Repository spring-cloud/spring-cloud-contract, pull requests merged in 2023-09, with the labels that each got.

#1937 https://github.com/spring-cloud/spring-cloud-contract/issues/1935
  spring-cloud-contract-stub-runner/src/main/java/org/springframework/cloud/contract/stubrunner/StubRunnerExecutor.java
Labels: bug

#1980 Cleanup Gradle deprecations
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/SpringCloudContractVerifierGradlePlugin.java
Labels: task

#1979 Print subprocess error when `generateContractTests` task fails
  spring-cloud-contract-tools/spring-cloud-contract-gradle-plugin/src/main/java/org/springframework/cloud/contract/verifier/plugin/GenerateServerTestsTask.java
Labels: enhancement

#1996 Use prepareTestInstance phase instead of beforeTestClass phase
  spring-cloud-contract-wiremock/src/main/java/org/springframework/cloud/contract/wiremock/WireMockTestExecutionListener.java
  spring-cloud-contract-wiremock/src/test/java/org/springframework/cloud/contract/wiremock/TestExecutionListenerAllowsOtherBeforeActionsTest.java
Labels: bug
